### ISSUE TITLE
Front와 Controller의 responsibility

### ISSUE THREAD

**Issue by objectio** [listenyoon/pwaTest#1]
[synopsis]
Front 클래스에서 메뉴의 정보에 대해 입력을 받고, 이를 Controller 클래스의 selectMenu()로 넘긴 다음, Cart 클래스의 addToCart()를 통해 Cart의 cartInfo 리스트에 저장됨.
이 때 Cart의 cartInfo가 리턴되어 Controller의 CartInfo에 저장이되고, 이 CartInfo가 Front 클래스의 CartItems에 저장이 되는 방식.
즉, 지금 상황은 Front와 Controller 클래스가 Cart 클래스 안의 CartInfo를 동일하게 가지고 가는 구조이다.

[problem]
* 그렇다면 Controller가 요청하는 requestCartInfo()의 존재 의의는?
    * 사실 requestCartInfo()를 confirmCartInfo()로 바꿔서 최대한 구조를 보존해보려고 생각했지만, 그렇게 되면 오히려 설계의 효용성이 좀 떨어지게 되는 상황이라.. 우리 팀한테 독이 될 듯함 ㅜ 아!!!!!!!!!!! ㅜ ㅜ 
* 이 상태면 Cart와 Order 클래스도 유명무실한 상황인듯?
    * Cart에 저장되는 cartInfo를 격리해서 저장해야 하는데 지금처럼 CartInfo를 Controller도 가지고 Front도 가지게 되는 상황이면 객체를 구분할 필요가 없어짐... 

그래서 팀원 여러분의 의견을 듣고 싶습니다..........................................

**Comment by objectio** [comment]
cartInfo 값을 리턴시키는 부분(Controller, Front에서 리턴되는 부분) 다 빼구, 장바구니에 담은 정보가 필요하면 requestCartInfo()를 여러 번 호출해서 CartInfo 데이터는 Cart에만 저장되게끔 하는 방식이 어떨지!
* Front --(requestCartInfo())--> Controller --(requestCartInfo())--> Cart
    * 원래 시퀀스 다이어그램처럼 cartInfo를 return해주되, 각 requestCartInfo() 메소드 안에 CartInfo가 지역변수로 선언되어서, Cart 이외에 다른 클래스에 CartInfo가 종속되지 않게 하는 방법이 가장 좋은듯!!

**Comment by objectio** [comment]
일단 위에 써놓은 내용을 fix/responsibility/#1 브랜치 따로 파서 코드 완성해서 올려놓았습니다!

**Comment by listenyoon** [comment]
> Cart의 cartInfo가 리턴되어 Controller의 CartInfo에 저장이되고, 이 CartInfo가 Front 클래스의 CartItems에 저장이 되는 방식.

확실히 요거때문에 계속 역할이 꼬였던거라 빼면 좀 나을듯하네요잉
