### ISSUE TITLE
의논하면 할 것들

### ISSUE THREAD

**Issue by rlawjd10** [listenyoon/pwaTest#3]
1. timeout이 되거나 init화면으로 돌아가는 부분 어떻게 할지
- 전체 while문으로 돌려서 주문이 끝나게 되면 바로 '주문을 시작하시겠습니까?'같은 메시지 출력하면서 다시 주문 반복하게 할지 
  or 프로그램을 종료시킬지
- 전자로 하게 되면 꽤나 고난이 예상되긴 함

2. endOrder()가 정확히 어떤 의미인지
-timeout()되면 영수증 출력과 상관없이 바로 endOrder()가 되는건지 or 시간 내에 영수증 출력을 선택하지 않으면 time out이 되어서 주문이 종료되는거? (그렇다면 이때 주문번호는 디폴트로 출력하는가)

3. 시퀀스 다이어그램에서 바코드랑 카드
-바코드를 사용하는 목적이 기프티콘인데 기프티콘 쿠폰 번호는 어떻게 할 것이며 잔액처리는 어떤 식으로 할 것인지...???? 코드로 어떻게 표현할지

4. 시퀀스 다이어그램에서 영수증 출력 / 주문번호 출력
 - 주문 번호 출력하는 부분을 별도의 시퀀스다이어그램으로 표현할까?

**Comment by objectio** [comment]
1. init 화면 돌아가는 거 없애고 프로그램 종료로
2. endOrder() 있되, 얘가 timeout 때 호출되는 건 아닌걸로
3. 2천원 할인쿠폰, 10% 20% 30% 할인쿠폰
4. 따로 시나리오를 나누지 말고 정상 결제 다이어그램에서 alternative로 표시해주기

**Comment by objectio** [comment]
## 6월 2일 새벽 회의록
### 앞으로 해야할 일들
1. GUI - `민영쓰`
2. 콘솔 코드 부분 수정 - `윤지쓰`
3. 시퀀스 다이어그램 시나리오 수정 - `전원` 금요일까지 완성해오기
4. PPT
    - 설계 클래스 다이어그램 - `정은쓰`
    - 설계 시퀀스 다이어그램 - `성윤쓰`
    - 주요 코드 설명 & 실행 결과 - `윤지쓰`
    - 분석 클래스 다이어그램 논외
5. 이번주 토요일 10시에 봅시다!
